version: "3.9"
name: music

services:
  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
      - "5433:5432"
    networks:
      - music
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U music" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MODE=docker
    networks:
      - music
    depends_on:
      db:
        condition: service_healthy

networks:
  music:
    ipam:
      driver: default
