package scale

// String returns scale name
func (s Type) String() string {
	return [...]string{
		// invalid
		"Invalid",

		// 3 notes, reference https://allthescales.org/scales.php?n=3
		"Minoric",

		// 4 notes, reference https://allthescales.org/scales.php?n=4
		"Thaptic", "Lothic", "Phratic", "Aerathic",
		"Epathic", "Mynic", "Rothic", "Eporic",
		"Zyphic", "Epogic", "Lanic", "Pyrric",
		"Aeoloric", "Gonic", "Dalic", "Dygic",
		"Daric", "Lonic", "Phradic", "Bolic",
		"Saric", "Zoptic", "Aeraphic", "Byptic",
		"Aeolic", "Koptic", "Mixolyric", "Lydic",
		"Stathic", "Dadic",
		"Phrynic",

		// 5 notes, reference https://allthescales.org/scales.php?n=5
		"Epathitonic", "Mynitonic", "Rocritonic", "Pentatonic", "Thaptitonic",
		"Magitonic", "Daditonic", "Aeolyphritonic", "Gycritonic", "Pyritonic",
		"Gathitonic", "Ionitonic", "Phrynitonic", "Stathitonic", "Thalitonic",
		"Zolitonic", "Epogitonic", "Lanitonic", "Paptitonic", "Ionacritonic",
		"Phraditonic", "Aeoloritonic", "Gonitonic", "Dalitonic", "Dygitonic",
		"Aeracritonic", "Byptitonic", "Daritonic", "Lonitonic", "Ionycritonic",
		"Lothitonic", "Phratonic", "Aerathitonic", "Saritonic", "Zoptitonic",
		"Dolitonic", "Poritonic", "Aerylitonic", "Zagitonic", "Lagitonic",
		"Molitonic", "Staptitonic", "Mothitonic", "Aeritonic", "Ragitonic",
		"Ionaditonic", "Bocritonic", "Gythitonic", "Pagitonic", "Aeolythitonic",
		"Zacritonic", "Laritonic", "Thacritonic", "Styditonic", "Loritonic",
		"Aeolyritonic", "Goritonic", "Aeoloditonic", "Doptitonic", "Aeraphitonic",
		"Zathitonic", "Raditonic", "Stonitonic", "Syptitonic", "Ionythitonic",
		"Aeolanitonic", "Danitonic", "Ionaritonic", "Dynitonic", "Zyditonic",
		"Aeolacritonic", "Zythitonic", "Dyritonic", "Koptitonic", "Thocritonic",
		"Lycritonic", "Daptitonic", "Kygitonic", "Mocritonic", "Zynitonic",
		"Epygitonic", "Zaptitonic", "Kagitonic", "Zogitonic", "Epyritonic",
		"Zothitonic", "Phrolitonic", "Ionagitonic", "Aeolapritonic", "Kyritonic",
		"Ionyptitonic", "Gyritonic", "Zalitonic", "Stolitonic", "Bylitonic",
		"Thoditonic", "Dogitonic", "Phralitonic", "Garitonic", "Soptitonic",
		"Kataritonic", "Sylitonic", "Thonitonic", "Phropitonic", "Staditonic",
		"Lyditonic", "Mythitonic", "Sogitonic", "Gothitonic", "Rothitonic",
		"Zylitonic", "Zoditonic", "Zaritonic", "Phrythitonic", "Rolitonic",
		"Ranitonic", "Laditonic", "Poditonic", "Ionothitonic", "Kanitonic",
		"Ryphitonic", "Gylitonic", "Aeolycritonic", "Pynitonic", "Zanitonic",
		"Phronitonic", "Banitonic", "Aeronitonic", "Golitonic", "Dyptitonic",
		"Aerynitonic", "Palitonic", "Stothitonic", "Aerophitonic", "Katagitonic",
		"Ionoditonic", "Bogitonic", "Mogitonic", "Docritonic", "Epaditonic",
		"Mixitonic", "Phrothitonic", "Katycritonic", "Ionalitonic", "Loptitonic",
		"Thyritonic", "Thoptitonic", "Bycritonic", "Pathitonic", "Myditonic",
		"Bolitonic", "Bothitonic", "Kataditonic", "Koditonic", "Tholitonic",

		// 6 notes, reference https://allthescales.org/scales.php?n=6
		"Epathimic", "Mynimic", "Rocrimic", "Eporimic", "Thaptimic", "Lothimic",
		"Dyrimic", "Koptimic", "Thocrimic", "Aeolanimic", "Danimic", "Ionarimic",
		"Daptimic", "Kygimic", "Mocrimic", "Zynimic", "Aeolimic", "Zythimic",
		"Epygimic", "Zaptimic", "Kagimic", "Zogimic", "Epyrimic", "Lycrimic",
		"Bylimic", "Zothimic", "Phrolimic", "Ionagimic", "Aeolaphimic", "Kycrimic",
		"Garimic", "Soptimic", "Ionyptimic", "Gyrimic", "Zalimic", "Stolimic",
		"Thonimic", "Stadimic", "Thodimic",
		"Mythimic", "Sogimic", "Gogimic", "Rothimic", "Katarimic", "Sylimic",
		"Mixolimic", "Dadimic", "Aeolyphimic", "Gycrimic", "Pyrimic", "Lydimic",
		"Ionacrimic", "Gathimic", "Ionynimic", "Phrynimic", "Stathimic", "Thatimic",
		"Dalimic", "Dygimic", "Zolimic", "Epogimic", "Lanimic", "Paptimic",
		"Darmic", "Lonimic", "Ionycrimic", "Phradimic", "Aeolorimic", "Gonimic",
		"Phracrimic", "Aerathimic", "Sarimic", "Zoptimic", "Zeracrimic", "Byptimic",
		"Starimic", "Phrathimic", "Saptimic", "Aerodimic", "Macrimic", "Rogimic",
		"Bygimic", "Thycrimic", "Aeoladimic", "Dylimic", "Eponimic", "Katygimic",
		"Stalimic", "Stoptimic", "Zygimic", "Kataptimic", "Aeolaptimic", "Pothimic",
		"Rycrimic", "Ronimic", "Stycrimic", "Katorimic", "Epythimic", "Kaptimic",
		"Katythimic", "Madimic", "Aerygimic", "Pylimic", "Ionathimic", "Morimic",
		"Aerycrimic", "Ganimic", "Eparimic", "Lyrimic", "Phraptimic", "Bacrimic",
		"Phralimic", "Phrogimic", "Rathimic", "Katocrimic", "Phryptimic", "Katynimic",
		"Solimic", "Ionolimic", "Ionophimic", "Aeologimic", "Zadimic", "Sygimic",
		"Thogimic", "Rythimic", "Donimic", "Aeoloptimic", "Panimic", "Lodimic",
		"Laptimic", "Lygimic", "Logimic", "Lalimic", "Sothimic", "Phrocrimic",
		"Modimic", "Barimic", "Poptimic", "Sagimic", "Aelothimic", "Socrimic",
		"Syrimic", "Stodimic", "Ionocrimic", "Zycrimic", "Ionygimic", "Katathimic",
		"Bolimic", "Bothimic", "Katadimic", "Kodimic", "Tholimic", "Ralimic",
		"Kanimic", "Zylimic", "Zodimic", "Zarimic", "Phrythimic", "Rorimic",
		"Pynimic", "Zanimic", "Ranimic", "Ladimic", "Podimic", "Ionothimic",
		"Kytrimic", "Golimic", "Dyptimic", "Ryrimic", "Gylimic", "Aeolycrimic",
		"Palimic", "Stothimic", "Aeronimic", "Katagimic", "Phronimic", "Banimic",
		"Ionodimic", "Bogimic", "Mogimic", "Docrimic", "Epadimic", "Aerynimic",
		"Mydimic", "Thyptimic", "Phrothimic", "Katycrimic", "Ionalimic", "Loptimic",
		"Zagimic", "Lagimic", "Thyrimic", "Thothimic", "Bycrimic", "Pathimic",
		"Mothimic", "Aeranimic", "Ragimic", "Dolimic", "Porimic", "Aerylimic",
		"Bocrimic", "Gythimic", "Pagimic", "Aeolythimic", "Molimic", "Staptimic",
		"Zacrimic", "Larimic", "Thacrimic", "Stydimic", "Lorimic", "Ionadimic",
		"Ionythimic", "Aerythimic",
		"Dynimic", "Zydimic", "Zathimic", "Radimic", "Stonimic", "Syptimic",
		"Ponimic", "Kadimic", "Gynimic", "Thydimic", "Polimic", "Thanimic",
		"Lathimic", "Aeralimic", "Kynimic", "Stynimic", "Epytimic", "Katoptimic",
		"Galimic", "Kathimic", "Lylimic", "Epalimic", "Epacrimic", "Sathimic",
		"Katanimic", "Katyrimic", "Rynimic", "Pogimic", "Aeraptimic", "Epylimic",
		"Manimic", "Marimic", "Locrimic", "Rylimic", "Epatimic", "Byrimic",
		"Kocrimic", "Korimic", "Lynimic", "Malimic", "Synimic", "Phragimic",
		"Mycrimic", "Ionorimic", "Phrydimic", "Zyptimic", "Katothimic", "Phrylimic",
		"Aerothimic", "Stagimic", "Dorimic", "Phrycrimic", "Kyptimic", "Ionylimic",
		"Epynimic", "Ionogimic", "Kydimic", "Gaptimic", "Tharimic", "Ionaphimic",
		"Thoptimic", "Bagimic", "Kyrimic", "Sonimic", "Aeolonimic", "Rygimic",
		"Thagimic", "Kolimic", "Dycrimic", "Epycrimic", "Gocrimic", "Katolimic",
		"Dagimic", "Aeolydimic", "Parimic", "Ionaptimic", "Thylimic", "Lolimic",
		"Thalimic", "Stygimic", "Aeolygimic", "Aerogimic", "Dacrimic", "Baptimic",
		"Stythimic", "Kothimic", "Pygimic", "Rodimic", "Sorimic", "Monimic",
		"Aeragimic", "Epothimic", "Salimic", "Lyptimic", "Katonimic", "Gygimic",
		"Aeradimic", "Zyrimic", "Stylimic",
		"Lythimic", "Dodimic", "Katalimic",
		"Boptimic", "Stogimic", "Thynimic", "Aeolathimic", "Bythimic", "Padimic",
		"Dathimic", "Epagimic", "Raptimic", "Epolimic", "Sythimic", "Sydimic",
		"Gacrimic", "Borimic", "Sycrimic", "Gadimic", "Aeolocrimic", "Phrygimic",
		"WholeTone",

		// 7 notes, reference https://allthescales.org/scales.php?n=7
		"Lydian", "Mixolydian", "Aeolian", "Locrian", "Ionian", "Dorian", "Phrygian",
		"Ionythian", "Aeolyrian", "Gorian", "Aeolodian", "Doptian", "Aeraphian", "Zacrian",
		"Ionarian", "Dynian", "Zydian", "Zathian", "Radian", "Stonian", "Syptian",
		"Aeolacrian", "Zythian", "Dyrian", "Koptian", "Thocrian", "Aeolanian", "Danian",
		"Zogian", "Epyrian", "Lycrian", "Daptian", "Kygian", "Mocrian", "Zynian",
		"Phrolian", "Ionagian", "Aeodian", "Kycrian", "Epygian", "Zaptian", "Kagian",
		"Soptian", "Ionyptian", "Gyrian", "Zalian", "Stolian", "Bylian", "Zothian",
		"Thonian", "Phrorian", "Stadian", "Thodian", "Dogian", "Mixopyrian", "Garian",
		"Epathian", "Mythian", "Sogian", "Gogian", "Rothian", "Katarian", "Stylian",
		"Stathian", "Mixonyphian", "Magian", "Dadian", "Aeolylian", "Gycrian", "Pyrian",
		"Epogian", "Lanian", "Paptian", "Ionacrian", "Gathian", "Ionyphian", "Phrynian",
		"Ionycrian", "Phradian", "Aeolorian", "Gonian", "Dalian", "Dygian", "Zolian",
		"Aerathian", "Sarian", "Zoptian", "Aeracrian", "Byptian", "Darian", "Lonian",
		"Aeopian", "Rygian", "Epynian", "Ionogian", "Kydian", "Gaptian", "Tharian",
		"Epycrian", "Gocrian", "Katolian", "Thoptian", "Bagian", "Kyrian", "Sonian",
		"Parian", "Ionaptian", "Thylian", "Lolian", "Thagian", "Kolian", "Dycrian",
		"Stygian", "Aeolygian", "Aerogian", "Dacrian", "Baptian", "Dagian", "Aeolydian",
		"Stythian", "Kothian", "Pygian", "Rodian", "Sorian", "Monian", "Thalian",
		"Zorian", "Aeragian", "Epothian", "Salian", "Lyptian", "Katonian", "Gyphian",
		"Thacrian", "Dodian", "Aeolyptian", "Aeolonian", "Aeradian", "Aeolagian", "Zyrian",
		"Aeolathian", "Bythian", "Padian", "Rolian", "Pydian", "Thygian", "Katalian",
		"Saptian", "Aerodian", "Macrian", "Rogian", "Boptian", "Stogian", "Thynian",
		"Thycrian", "Aeoladian", "Dylian", "Eponian", "Katygian", "Starian", "Phrathian",
		"Stalian", "Stoptian", "Zygian", "Kataptian", "Aeolaptian", "Pothian", "Bygian",
		"Morian", "Rycrian", "Ronian", "Stycrian", "Katorian", "Epythian", "Kaptian",
		"Phraptian", "Bacrian", "Katythian", "Madian", "Aerygian", "Pylian", "Ionathian",
		"Katocrian", "Phryptian", "Katynian", "Aerycrian", "Ganian", "Eparian", "Lyrian",
		"Ionopian", "Aeologian", "Zadian", "Sygian", "Phralian", "Phrogian", "Rathian",
		"Rythian", "Donian", "Aeoloptian", "Panian", "Lodian", "Solian", "Ionolian",
		"Laptian", "Lygian", "Logian", "Lalian", "Sothian", "Phrocrian", "Thogian",
		"Katathian", "Modian", "Barian", "Mixolocrian", "Sagian", "Aeolothian", "Socrian",
		"Tholian", "Ralian", "Syrian", "Stodian", "Ionocrian", "Zycrian", "Ionygian",
		"Zarian", "Phrythian", "Rorian", "Bolian", "Bothian", "Katadian", "Kodian",
		"Ranian", "Ladian", "Podian", "Ionothian", "Kanian", "Zylian", "Zodian",
		"Golian", "Dyptian", "Ryphian", "Gylian", "Aeolycrian", "Pynian", "Zanian",
		"Palian", "Stothian", "Aerorian", "Katagian", "Phronian", "Banian", "Aeronian",
		"Loptian", "Ionodian", "Bogian", "Mogian", "Docrian", "Epadian", "Aerynian",
		"Bycrian", "Pathian", "Mydian", "Thyptian", "Phrothian", "Katycrian", "Ionalian",
		"Dolian", "Porian", "Aerylian", "Zagian", "Lagian", "Tyrian", "Mixonorian",
		"Pagian", "Aeolythian", "Molian", "Staptian", "Mothian", "Aeranian", "Ragian",
		"Larian", "Lythian", "Stydian", "Lorian", "Ionadian", "Bocrian", "Mixolythian",
		"Thadian", "Sanian", "Ionydian", "Epydian", "Katydian", "Mathian", "Aeryptian",
		"Pythian", "Katylian", "Bydian", "Bynian", "Galian", "Zonian", "Myrian",
		"Katogian", "Stacrian", "Styrian", "Ionyrian", "Phrodian", "Pycrian", "Gyptian",
		"Katacrian", "Sodian", "Bathian", "Mylian", "Godian", "Thorian", "Zocrian",
		"Stanian", "Epanian", "Konian", "Stocrian", "Kalian", "Phroptian", "Dydian",
		"Katyptian", "Epodian", "Mygian", "Pacrian", "Aerocrian", "Aeolarian", "Kythian",
		"Bonian", "Badian", "Katodian", "Sadian", "Dothian", "Moptian", "Aeryrian",
		"Epagian", "Raptian", "Epolian", "Sythian", "Sydian", "Epocrian", "Kylian",
		"Gacrian", "Borian", "Sycrian", "Gadian", "Aeolocrian", "Mixodorian", "Dathian",
		"Katoptian", "Ponian", "Kadian", "Gynian", "Thyphian", "Polian", "Thanian",
		"Epacrian", "Sathian", "Lathian", "Aeralian", "Kynian", "Stynian", "Epyphian",
		"Pogian", "Aeraptian", "Epylian", "Gamian", "Kathian", "Lylian", "Epalian",
		"Eporian", "Rylian", "Epaptian", "Byrian", "Katanian", "Katyrian", "Rynian",
		"Korian", "Lynian", "Malian", "Synian", "Phragian", "Manian", "Marian",
		"Mycrian", "Ionorian", "Phrydian", "Zyptian", "Katothian", "Phrylian", "Kocrian",
		"Ionanian", "Aerothian", "Stagian", "Lothian", "Phrycrian", "Kyptian", "Ionylian",
		"Gydian", "Kogian", "Rarian", "Aerolian", "Karian", "Myptian", "Rydian",
		"Aeolynian", "Aeroptian", "Phryrian", "Gothian", "Storian", "Pyptian", "Thydian",

		// 8 notes, reference https://allthescales.org/scales.php?n=8
		"Aerycryllic", "Gadyllic", "Solyllic", "Zylyllic", "Mixodyllic", "Soryllic", "Godyllic", "Epiphyllic",
		"Pynyllic", "Bocryllic", "Kogyllic", "Raryllic", "Zycryllic", "Mycryllic", "Laptyllic", "Pylyllic",
		"Pothyllic", "Phronyllic", "Stynyllic", "Rathyllic", "Aeryptyllic", "Zydyllic", "Katolyllic", "Rythyllic",
		"Locryllic", "Bylyllic", "Sogyllic", "Ionycryllic", "Koptyllic", "Epyryllic", "Soptyllic", "Aeolylyllic",
		"Aeracryllic", "Epygyllic", "Thonyllic", "Lanyllic", "Phrynyllic", "Lycryllic", "Ionyptyllic", "Epathyllic",
		"Dydyllic", "Thogyllic", "Rygyllic", "Bycryllic", "Zacryllic", "Panyllic", "Dyryllic", "Zathyllic",
		"Dagyllic", "Katalyllic", "Katoryllic", "Dodyllic", "Zogyllic", "Madyllic", "Dycryllic", "Aeologyllic",
		"Sydyllic", "Katogyllic", "Zygyllic", "Aeralyllic",
		"Bacryllic", "Aerygyllic", "Dathyllic", "Boptyllic", "Bagyllic", "Mathyllic", "Styptyllic", "Zolyllic",
		"Rocryllic", "Zyryllic", "Sagyllic", "Epinyllic", "Katagyllic", "Ragyllic", "Gothyllic", "Lythyllic",
		"Ionocryllic", "Gocryllic", "Epiryllic", "Aeradyllic", "Staptyllic", "Danyllic", "Goptyllic", "Epocryllic",
		"Ionoptyllic", "Aeoloryllic", "Thydyllic", "Gycryllic", "Lyryllic", "Mogyllic", "Katodyllic", "Moptyllic",
		"Dolyllic", "Moryllic", "Bydyllic", "Pocryllic", "Phracryllic", "Gyryllic", "Phrygyllic", "Dogyllic",
		"Thagyllic", "Thoptyllic", "Phraptyllic", "Gylyllic", "Phralyllic", "Dygyllic", "Ronyllic", "Epogyllic",
		"Aeoladyllic", "Kocryllic", "Lodyllic", "Bynyllic", "Kydyllic", "Bygyllic", "Phryptyllic", "Ionayllic",
		"Phroryllic", "Thyphyllic", "Poptyllic", "Mixonyllic", "Paptyllic", "Storyllic", "Phrycryllic", "Palyllic",
		"Phranyllic", "Stydyllic", "Zadyllic", "Zalyllic", "Zocryllic", "Katocryllic", "Aerathyllic", "Stoptyllic",
		"Lydyllic", "Radyllic", "Stagyllic", "Ionoryllic", "Phrodyllic", "Aeragyllic", "Banyllic", "Epothyllic",
		"Zoryllic", "Phrolyllic", "Kolyllic", "Thodyllic", "Socryllic", "Aeolyllic", "Zythyllic", "Aeoryllic",
		"Mixolydyllic", "Mixonyphyllic", "Aeolanyllic", "Thocryllic", "Kygyllic", "Ionagyllic", "Gogyllic", "Phradyllic",
		"Ioniptyllic", "Kycryllic", "Aeolaptyllic", "Rodyllic", "Ionathyllic", "Pythyllic", "Zonyllic", "Ryryllic",
		"Aeolothyllic", "Ionyryllic", "Rydyllic", "Gonyllic", "Rolyllic", "Katydyllic", "Zyptyllic", "Modyllic",
		"Maptyllic", "Aeraptyllic", "Katadyllic", "Magyllic", "Phrylyllic", "Epigyllic", "Molyllic", "Ponyllic",
		"Thyptyllic", "Ionogyllic", "Aeolaryllic", "Katygyllic", "Ganyllic", "Kyptyllic", "Salyllic", "Sanyllic",
		"Doptyllic", "Ionilyllic", "Manyllic", "Polyllic", "Stanyllic", "Mixotharyllic", "Eporyllic", "Aerynyllic",
		"Lonyllic", "Sathyllic", "Layllic", "Saryllic", "Thacryllic", "Aeolynyllic", "Thadyllic", "Lynyllic",
		"Aeolathyllic", "Aeolocryllic", "Phroptyllic", "Kodyllic", "Epaptyllic", "Ionoyllic", "Gyptyllic", "Aerythyllic",
		"Zagyllic", "Epacryllic", "Thorcryllic", "Loptyllic", "Katylyllic", "Malyllic", "Mydyllic", "Thycryllic",
		"Gythyllic", "Pyryllic", "Rycryllic", "Phrathyllic", "Badyllic", "Phrocryllic", "Staryllic", "Zothyllic",
		"Tharyllic", "Sylyllic", "Lothyllic", "Daryllic", "Monyllic", "Styryllic", "Aeolacryllic", "Raptyllic",
		"Kataryllic", "Aerocryllic", "Zanyllic", "Aeolonyllic", "Aeonyllic", "Kyryllic", "Sythyllic", "Katycryllic",
		"Stogyllic", "Ionidyllic", "Stonyllic", "Stalyllic", "Poryllic", "Mocryllic", "Aeolyryllic", "Baryllic",
		"Dalyllic", "Ionyphyllic", "Zaptyllic", "Garyllic", "Gathyllic", "Mixopyryllic", "Ionacryllic", "Stylyllic",
		"Stycryllic", "Ionothyllic", "Mythyllic", "Aerylyllic", "Bonyllic", "Tholyllic", "Katyryllic", "Sadyllic",
		"Stolyllic", "Logyllic", "Dacryllic", "Thynyllic", "Gydyllic", "Eparyllic", "Dynyllic", "Ionyllic",
		"Zaryllic", "Dythyllic", "Ionaryllic", "Laryllic", "Kataptyllic", "Sonyllic", "Pathyllic", "Loryllic",
		"Aeronyllic", "Pycryllic", "Mygyllic", "Lylyllic", "Daptyllic", "Ioninyllic", "Epaphyllic", "Lolyllic",
		"Stacryllic", "Doryllic", "Kadyllic", "Rynyllic", "Aerogyllic", "Rothyllic", "Kagyllic", "Stathyllic",
		"Thyryllic", "Gygyllic", "Sodyllic", "Goryllic", "Bothyllic", "Gynyllic", "Ionaptyllic", "Phryryllic",
		"Racryllic", "Epicryllic", "Stygyllic", "Syryllic", "Stythyllic", "Aerothyllic", "Mixoryllic", "Thanyllic",
		"Roryllic", "Epotyllic", "Epidyllic", "Kaptyllic",
		"MajorDiminished", "MinorDiminished",

		// 9 notes, reference https://allthescales.org/scales.php?n=9
		"Aerycrygic", "Gadygic", "Solygic", "Zylygic", "Garygic", "Sorygic", "Godygic", "Epithygic", "Ionoptygic",
		"Kalygic", "Ionodygic", "Bythygic", "Epygic", "Marygic", "Gaptygic", "Aeroptygic", "Mylygic", "Galygic",
		"Mixolydygic", "Ionycrygic", "Zoptygic", "Phrygygic", "Locrygic", "Gonygic", "Aeracrygic", "Aerathygic", "Dorygic",
		"Dycrygic", "Aeolygic", "Dydygic", "Tholygic", "Rynygic", "Bycrygic", "Zacrygic", "Panygic", "Dyrygic",
		"Loptygic", "Katylygic", "Phradygic", "Mixodygic", "Katalygic", "Katorygic", "Dogygic", "Zodygic", "Madygic",
		"Bagygic", "Mathygic", "Styptygic", "Zolygic", "Sydygic", "Katygic", "Zyphygic", "Aeralygic", "Ryptygic",
		"Apinygic", "Katagygic", "Radygic", "Gothygic", "Lythygic", "Bacrygic", "Aerygic", "Dathygic", "Boptygic",
		"Epyrygic", "Aeradygic", "Staptygic", "Danygic", "Goptygic", "Epocrygic", "Rocrygic", "Zyrygic", "Sadygic",
		"Aeolorygic", "Thydygic", "Gycrygic", "Lyrygic", "Modygic", "Katodygic", "Moptygic", "Ionocrygic", "Gocrygic",
		"Manygic", "Polygic", "Stanygic", "Thaptygic", "Eporygic", "Aerynygic", "Thyptygic", "Ionogygic", "Aeolarygic",
		"Sathygic", "Ladygic", "Sarygic", "Thacrygic", "Aeolynygic", "Thadygic", "Lynygic", "Doptygic", "Ionilygic",
		"Phrygic", "Aeranygic", "Dothygic", "Lydygic", "Stadygic", "Byptygic", "Stodygic", "Zynygic", "Lonygic",
		"Zothygic", "Aeolathygic", "Aeolocrygic", "Phroptygic", "Kodygic", "Eparygic", "Ionygic", "Gyptygic", "Aerythygic",
		"Aeolacrygic", "Raptygic", "Gythygic", "Pyrygic", "Rycrygic", "Phrathygic", "Badygic", "Phrocrygic", "Starygic",
		"Kyrygic", "Sythygic", "Katycrygic", "Tharygic", "Sylygic", "Lothygic", "Darygic", "Monygic", "Styrygic",
		"Porygic", "Mocrygic", "Aeolyrygic", "Barygic", "Katarygic", "Aerocrygic", "Zanygic", "Aeolonygic", "Aeolanygic",
		"Kaptygic", "Sacrygic", "Padygic", "Epilygic", "Kynygic", "Stophygic", "Ionidygic", "Stonygic", "Stalygic",
		"Koptygic", "Raphygic", "Zycrygic", "Mycrygic", "Laptygic", "Pylygic", "Rodygic", "Epolygic", "Epidygic",
		"Phronygic", "Stynygic", "Zydygic",

		// 10 notes, reference https://allthescales.org/scales.php?n=10
		"Aerycryllian", "Gadyllian", "Solyllian", "Zyphyllian", "Garyllian", "Soryllian", "Godyllian", "Epityllian", "Ionyllian", "Aeoryllian",
		"Katoryllian", "Dodyllian", "Zogyllian", "Madyllian", "Dycryllian", "Aeogyllian", "Dydyllian", "Thogyllian", "Rygyllian", "Bathyllian",
		"Sydyllian", "Katogyllian", "Mixodyllian", "Aeradyllian", "Ryptyllian", "Loptyllian", "Kataphyllian", "Phradyllian", "Dagyllian", "Katyllian",
		"Gothyllian", "Lythyllian", "Bacryllian", "Aerygyllian", "Dathyllian", "Boptyllian", "Bagyllian", "Mathyllian", "Styptyllian", "Zolyllian",
		"Staptyllian", "Danyllian", "Goptyllian", "Epocryllian", "Rocryllian", "Zyryllian", "Sagyllian", "Epinyllian", "Katagyllian", "Ragyllian",
		"Thydyllian", "Epiryllian", "Lyryllian", "Mogyllian", "Katodyllian",
	}[s]
}
